@startuml
title webrtc signaling

participant CallActivity <<(I,#ADD1B2)  SignalingEvents >> <<(I,#ADD1B2)  PeerConnectionEvents >>

participant DirectRTCClient <<(I,#ADD1B2)  AppRTCClient >> <<(I,#ADD1B2)  TCPChannelEvents >>

participant PeerConnectionClient

participant PeerConnectionFactory
participant PeerConnection
participant PeerConnection.Observer
participant SdpObserver

CallActivity -> DirectRTCClient:  appRtcClient = \nnew DirectRTCClient(SignalingEvents=CallActivity)
DirectRTCClient->DirectRTCClient: sigEvents = CallActivity
CallActivity -> PeerConnectionClient:  peerConnectionClient = \nnew PeerConnectionClient(PeerConnectionEvents=CallActivity)
PeerConnectionClient->PeerConnectionClient:  pcEvents = CallActivity
PeerConnectionClient->PeerConnection.Observer:  pcObserver = new PeerConnection.Observer()
PeerConnectionClient->SdpObserver:  sdpObserver = new SdpObserver()
PeerConnectionClient->PeerConnectionFactory: initialize()
CallActivity -> PeerConnectionClient:  peerConnectionClient.createPeerConnectionFactory(options)
PeerConnectionClient->PeerConnectionFactory: factory = PeerConnectionFactory.builder()\n.createPeerConnectionFactory()


CallActivity -> DirectRTCClient:  appRtcClient.connectToRoom(roomConnectionParameters)
...a moment latter...
DirectRTCClient -> DirectRTCClient:  onTCPConnected(isServer)  <color #00FF00> // Ev_MT_GetOffer_Cmd </color>
DirectRTCClient -> CallActivity:  sigEvents.onConnectedToRoom(SignalingParameters)
CallActivity -> PeerConnectionClient:  peerConnectionClient.createPeerConnection(..., signalingParameters)
PeerConnectionClient -> PeerConnectionClient:  createMediaConstraints
PeerConnectionClient->PeerConnectionFactory: peerConnection = \nfactory.createPeerConnection(rtcConfig, pcObserver)\n//<color #118888>TODO observer callback</color>
PeerConnectionFactory->PeerConnection: createPeerConnection(pcObserver)
PeerConnectionClient -> PeerConnectionClient:  peerConnection.addTrack
CallActivity -> PeerConnectionClient:  peerConnectionClient.createOffer(..., signalingParameters)
PeerConnectionClient->PeerConnection: peerConnection.createOffer(sdpObserver, sdpMediaConstraints)
SdpObserver->PeerConnectionClient: onCreateSuccess(SessionDescription sdp)
PeerConnectionClient->PeerConnection: peerConnection.setLocalDescription(sdpObserver, sdp)
SdpObserver->PeerConnectionClient: onSetSuccess()
PeerConnectionClient->CallActivity: pcEvents.onLocalDescription(sdp)
CallActivity -> DirectRTCClient:  appRtcClient.sendOfferSdp(sdp) <color #00FF00> // Ev_MT_GetOffer_Ntf </color>
...a moment latter...
DirectRTCClient -> DirectRTCClient:  onTCPMessage(String msg) <color #00FF00> // Ev_MT_SetAnswer_Cmd </color>
DirectRTCClient -> CallActivity:  sigEvents.onRemoteDescription(sdp)
CallActivity -> PeerConnectionClient:  peerConnectionClient.setRemoteDescription(sdp)
PeerConnectionClient->PeerConnection: peerConnection.setRemoteDescription(sdpObserver, sdpRemote)
SdpObserver->PeerConnectionClient: onSetSuccess()
PeerConnectionClient->PeerConnection: peerConnection.addIceCandidate(candidate)
PeerConnection->PeerConnectionClient: pcObserver.onIceCandidate(candidate)
PeerConnectionClient->CallActivity: pcEvents.onIceCandidate(candidate)
CallActivity -> DirectRTCClient:  appRtcClient.sendLocalIceCandidate(candidate)  <color #00FF00> // Ev_MT_IceCandidate_Ntf </color>
...a moment latter...
DirectRTCClient -> DirectRTCClient:  onTCPMessage(String msg) <color #00FF00> // Ev_MT_SetIceCandidate_Cmd </color>
DirectRTCClient -> CallActivity:  sigEvents.onRemoteIceCandidate(candidates)
CallActivity -> PeerConnectionClient:  peerConnectionClient.addRemoteIceCandidate(candidate)
PeerConnectionClient->PeerConnection: peerConnection.addIceCandidate(candidate)
'PeerConnectionClient
'Alice -> Alice: PeerConnectionFactory.builder()\n.createPeerConnectionFactory()
'Alice -> Bob: establish connect
'Bob --> Alice: connected //onConnectedToRoom
'Alice --> Alice: createMediaConstraints()
'Alice --> Alice: createPeerConnection(\nrtcConfig,\n pcObserver)
'Alice --> Alice: createOffer(\nsdpObserver, \nsdpMediaConstraints)
'Alice --> Alice: sdpObserver.onCreateSuccess(sdp)
'Alice --> Alice: setLocalDescription(sdpObserver, sdp)
'Alice --> Alice: sdpObserver.onSetSuccess()


'Alice -> Bob: Another authentication Request
'Alice <-- Bob: another authentication Response
@enduml